import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

// Flat config (ESLint 9). Standard Vite + React + TypeScript setup.
// `generated/` is excluded — it is autogenerated by the managed-apps `ms` CLI.
export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "generated",
      ".vite-cache",
      "*.timestamp-*.mjs",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // Make the "use the installed package, not the familiar-but-wrong one"
      // guidance enforceable instead of prose-only. These specifiers resolve
      // transitively (e.g. framer-motion via motion, @radix-ui/react-* via the
      // unified radix-ui package), so without this rule a wrong import would
      // type-check and build cleanly — then drift from the template's intent.
      // `bun run check` runs lint, so this fails the check.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["framer-motion"],
              message:
                "Use `motion/react` instead (e.g. `import { motion, AnimatePresence } from \"motion/react\"`).",
            },
            {
              group: ["@radix-ui/react-*"],
              message:
                "Import Radix primitives from the unified `radix-ui` package (e.g. `import { Dialog } from \"radix-ui\"`), or use the vendored `@/components/ui/*` wrappers.",
            },
            {
              group: ["next", "next/*"],
              message:
                "This is a Vite SPA, not Next.js. Use react-router-dom for routing and plain modules — there is no `next` runtime.",
            },
            {
              group: ["redux", "react-redux", "jotai", "recoil"],
              message:
                "Use the pre-wired zustand store (`@/lib/store`) for shared state.",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "MemberExpression[object.name='window'][property.name=/^(parent|top)$/]",
          message:
            "Parent-frame access is restricted to the locked console-capture and Cowork transport modules.",
        },
        {
          selector:
            "CallExpression[callee.name='postMessage'], CallExpression[callee.property.name='postMessage']",
          message:
            "postMessage is restricted to the locked console-capture and Cowork transport modules.",
        },
      ],
    },
  },
  {
    files: [
      "src/lib/console-capture.ts",
      "src/lib/cowork-parent-transport.ts",
      "src/lib/app-mounted-transport.ts",
      "src/lib/app-view-transport.ts",
    ],
    rules: {
      // Defense-in-depth for direct literal calls. The Python source-contract
      // guard pins the variable-backed runtime sender to its exact origin set.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.name='postMessage'] Literal[value='*'], CallExpression[callee.property.name='postMessage'] Literal[value='*']",
          message:
            "Parent-frame messages must not use a direct wildcard target-origin literal.",
        },
      ],
    },
  },
  {
    // shadcn/ui components are vendored + pre-installed (the agent must not edit
    // them). They intentionally co-export a component plus its `cva` variants
    // (e.g. `buttonVariants`), which trips react-refresh. Silence the rule for the
    // ui/ directory only — it stays active for the agent's own pages/components.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // `vite-dev-reload.ts` is inlined scaffold infra (the SSE dev-reload Vite
    // plugin — the agent must not edit it). It intercepts Vite's internal HMR
    // WebSocket payloads and Connect-style req/res objects, which are untyped,
    // and uses best-effort empty `catch {}` blocks around fire-and-forget
    // broadcasts. Silence `no-explicit-any` / `no-empty` for this one file —
    // both stay active for the agent's own code.
    files: ["vite-dev-reload.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-empty": "off",
    },
  }
);
